### ISSUE TITLE
访问不到页面

### ISSUE THREAD

**Issue by Lyf888lyf** [7Rocky/gtfobins-cli#1]
850  git clone https://github.com/7Rocky/gtfobins-cli.git
  851  ls
  852  cd gtfobins-cli
  853  ls
  854  ls -al
  855  echo $PATH
  856  cd
  857  python3 ~/Tools/gtfobins-cli/gtfobins-cli.py --sudo arp
  858  python3 ~/Tools/gtfobins-cli/gtfobins-cli.py arp
  859  cd Tools/gtfobins-cli
  860  ls
  861  ./gtfobins-cli.py arp
  862  cd
  863  export http_proxy="172.20.10.5:7897"\nexport https_proxy="172.20.10.5:7897"\n
  864  ls
  865  python3 ~/Tools/gtfobins-cli/gtfobins-cli.py arp
  866  ip a
  867  whereis export
  868  echo $https_proyx
  869  echo $https_proxy
  870  ping 127.20.10.5
  871  ping 172.20.10.5
  872  export http_proxy="http://172.20.10.5:7897"\nexport https_proxy="http://172.20.10.5:7897"\n

┌──(root㉿kali)-[~]
└─# python3 ~/Tools/gtfobins-cli/gtfobins-cli.py arp

Could not load page

Search on: https://gtfobins.github.io/

┌──(root㉿kali)-[~]
└─# echo $https_proxy

http://172.20.10.5:7897

**Comment by 7Rocky** [comment]
That looks like a problem with your `HTTPS_PROXY` environment variable or your actual proxy, not with `gtfobins-cli`.
